"""Export deterministic Titanic model evidence for the standalone website."""

from __future__ import annotations

import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
APP_DIR = ROOT / "apps" / "titanic_survival_game"
sys.path.insert(0, str(APP_DIR))

from titanic_game.data import load_titanic, prepare_features  # noqa: E402
from titanic_game.model import explanation_frame, predict_survival, train_models  # noqa: E402


PASSENGER_IDS = [2, 8, 15, 21, 22, 184]


def clean_name(name: str) -> str:
    surname, rest = name.split(",", 1)
    return f"{rest.strip()} {surname.strip()}"


def main() -> None:
    frame = load_titanic()
    prepared = prepare_features(frame)
    models = train_models(frame, random_state=42)
    bundle = models["Logistic regression"]

    passengers = []
    for passenger_id in PASSENGER_IDS:
        row = frame.loc[frame["PassengerId"] == passenger_id].iloc[0]
        one = frame.loc[[row.name]]
        explanation = explanation_frame(bundle, one)
        age = None if row.isna()["Age"] else float(row["Age"])
        family_size = int(row["SibSp"] + row["Parch"] + 1)
        passengers.append(
            {
                "id": f"p{passenger_id}",
                "passengerId": passenger_id,
                "name": clean_name(str(row["Name"])),
                "sex": str(row["Sex"]),
                "age": age,
                "pclass": int(row["Pclass"]),
                "familySize": family_size,
                "fare": round(float(row["Fare"]), 2),
                "embarked": str(row["Embarked"]),
                "historicalOutcome": int(row["Survived"]),
                "probability": round(predict_survival(bundle, one), 4),
                "factors": [
                    {
                        "feature": str(item["feature"]),
                        "impact": round(float(item["impact"]), 4),
                        "direction": str(item["direction"]),
                    }
                    for item in explanation.to_dict("records")[:5]
                ],
            }
        )

    sex_rates = frame.groupby("Sex")["Survived"].mean().to_dict()
    class_rates = frame.groupby("Pclass")["Survived"].mean().to_dict()
    report = {
        "generatedFrom": "data/Kaggle_titanic_dataset/Titanic-Dataset.csv",
        "trainingRows": int(len(frame)),
        "model": {
            "name": "Logistic regression",
            "metrics": {key: round(float(value), 4) for key, value in bundle.metrics.items()},
            "comparison": {
                name: {key: round(float(value), 4) for key, value in model.metrics.items()}
                for name, model in models.items()
            },
        },
        "dataset": {
            "survivalRate": round(float(frame["Survived"].mean()), 4),
            "femaleSurvivalRate": round(float(sex_rates["female"]), 4),
            "maleSurvivalRate": round(float(sex_rates["male"]), 4),
            "classSurvivalRates": {
                str(key): round(float(value), 4) for key, value in class_rates.items()
            },
            "missingAgeRate": round(float(frame["Age"].isna().mean()), 4),
            "missingCabinRate": round(float(frame["Cabin"].isna().mean()), 4),
        },
        "passengers": passengers,
    }

    output = ROOT / "website" / "data" / "model-results.js"
    output.write_text(
        "// Generated by scripts/export_model_report.py\n"
        f"export const MODEL_REPORT = Object.freeze({json.dumps(report, ensure_ascii=False, indent=2)});\n",
        encoding="utf-8",
    )
    print(f"Wrote {output.relative_to(ROOT)} with {len(passengers)} historical passengers")


if __name__ == "__main__":
    main()
